version: 2

models:
  - name: customers
    description: This table has basic information about a customer
    columns:
        - name: customer_id
          description: This is a unique identifier for a customer
          tests:
            - unique
            - not_null
        
        - name: first_name
          description: Customer's first name. PII.

        - name: last_name
          description: Customer's last name. PII.

        - name: email
          description: Customer's email address. PII.
